### ISSUE TITLE
Popup when user hover to profile

### ISSUE THREAD

**Issue by hcupiter** [pewpewnor/HyperSpace#21]
Daritadi masih belom kepikiran cara supaya keluar pop up kalo user hover ke profile picturenya di halaman home untuk membuka button yang menuju myprofile dan sign out (lihat referensi figma)

**Comment by pewpewnor** [comment]
https://www.youtube.com/watch?v=9DwGahSqcEc ??

**Comment by pewpewnor** [comment]
Use css hover i guess
