### ISSUE TITLE
Fix CSS for thread component

### ISSUE THREAD

**Issue by pewpewnor** [pewpewnor/HyperSpace#33]
- [ ] Make thread text bigger
- [ ] Make thread info text bigger
- [ ] Make profile picture into a circle using CSS

**Comment by pewpewnor** [comment]
![image](https://user-images.githubusercontent.com/125549982/224342541-b869fc69-cabb-4a2b-9d80-c77af1ca75cf.png)
Text is still too small

**Comment by rajat62** [comment]
// thread info text bigger
.thread__container__top > .thread__info > .thread__info__date__container > .thread__info__date{
	font-size: 1rem;
}

// Profile Picture rounded

.thread__container__top > .thread__profile__container > img {
	width: 2.438rem;
	height: 2.438rem;
	border-radius: 50%;
}

**Comment by rajat62** [comment]
![Updated Design](https://user-images.githubusercontent.com/107788563/229841014-4b684505-d1c3-4085-9a8a-de3d193f3a0b.png)

**Comment by rajat62** [comment]
Are these changes ok?
