### ISSUE TITLE
Fix icon color in navbar and thread

### ISSUE THREAD

**Issue by pewpewnor** [pewpewnor/HyperSpace#41]
- [x] Fix crown icon color in navbar (user information)
- [x] Fix thread icon color in space (user information)

**Comment by pewpewnor** [comment]
Change icon color to yellow in here:

![image](https://user-images.githubusercontent.com/125549982/223348318-93f2af76-4bf6-4620-9437-1f1ca91d4323.png)
![image](https://user-images.githubusercontent.com/125549982/223348457-1b6309d4-c8e1-4b52-b54c-c0332fecc06a.png)

**Comment by SudarshanSirsi** [comment]
Hello Pewpewnor,
I am new to the open source community, I want to update my skills and I think I can handle this task. Will you assign this to me?

**Comment by pewpewnor** [comment]
Sure @SudarshanSirsi go ahead!

**Comment by pewpewnor** [comment]
@KetsunoAna117
You haven't work on this issue yet, right?

**Comment by SudarshanSirsi** [comment]
Thank you @pewpewnor I'll get back to you once it's done.
