### ISSUE TITLE
Needs login page

### ISSUE THREAD

**Issue by pewpewnor** [pewpewnor/HyperSpace#9]
The project needs login components to make up the login page in the /src/pages/login

- [x] Username and password input fields
- [x] Error field for displaying error message
- [x] Functionality for fields
- [x] CSS for login page
- [x] Responsive CSS

**Comment by pewpewnor** [comment]
Something like this:

![image](https://user-images.githubusercontent.com/125549982/223345546-9ddfc517-ad6f-45cd-b387-2fe12b405be0.png)

**Comment by rajat62** [comment]
[login.txt](https://github.com/pewpewnor/HyperSpace/files/11151430/login.txt)
[css.txt](https://github.com/pewpewnor/HyperSpace/files/11151431/css.txt)

// Have username and password field
// Display wrong username is does not matches the string
// Form is working
// Implemented CSS
// Responsive also
![1](https://user-images.githubusercontent.com/107788563/229876406-f5e85538-4dbc-4404-b09b-28e43d96caa8.png)
![2](https://user-images.githubusercontent.com/107788563/229876427-9a4e9187-7a91-485c-9906-a56cfbb2e8d9.png)

**Comment by pewpewnor** [comment]
Hello Rajat, I am sorry for my delayed response. Our project development is currently suspended due to some real-life issues. However, I really appreciate your version of the login page. I have also added some functionalities to real branch, but unfortunately, I cannot continue the development at this time. I apologize sincerely.

**Comment by rajat62** [comment]
No problem at all! I completely understand.
